spring:
  application:
      name: ace-oauth-server
  redis:
      database: 1
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      pool:
          max-active: 20
  datasource:
      name: oauth
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ag_oauth?useUnicode=true&characterEncoding=UTF8
      username: root
      password: 123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  thymeleaf:
      mode: LEGACYHTML5
      cache: false

server:
  port: 9999
  context-path: /uaa

logging:
  level:
    root: info
    ## 这里设置为info，是因为如果不设置，debug时会不断打印mq日志。
    org.springframework.integration.endpoint.SourcePollingChannelAdapter: info
    org.springframework.security: DEBUG

redis:
  aec-key: xx288&^^%$!@#4dc
  aec-iv: 0123456789abcdef
